### ISSUE TITLE
Can we support UDP?

### ISSUE THREAD

**Issue by rampageX** [rofl0r/rrredir#3]
Very nice RR function, if it support UDP then can be better!

**Comment by rofl0r** [comment]
thinking about it... as UDP does not indicate whether a packet reached its destination, there's little point in having round robin functionality - you cannot dected whether first target is offline or online. did i miss something?

**Comment by rampageX** [comment]
Oh, that's it. It's no wonder that the other udp_load_balancer projects I saw on github were simple and sloppy, using random send methods, and did not detect upstream server availability.
