### ISSUE TITLE
set timeout < 1 no effect?

### ISSUE THREAD

**Issue by rampageX** [rofl0r/rrredir#5]
I try use rrredir with some dns server with tcp support, timeout=1 working great:

`rrredir -t 1 -p 6666 1.1.1.1:53 9.9.9.9:9953 208.67.222.222:443 208.67.220.220:443`

I set the first up steam with 1.1.1.1:53 on purpose, because it is not support tcp.

> dig @127.0.0.1 -p 6666 twitter.com +tcp
> ......
> ......
> ;; Query time: 1200 msec
> ;; MSG SIZE  rcvd: 72

1200ms ~ timeout + query time, it's ok.

but when i set timeout=0.5:

`rrredir -t 0.5 -p 6666 1.1.1.1:53 9.9.9.9:9953 208.67.222.222:443 208.67.220.220:443`

then `dig` goes time out:

digg @127.0.0.1 -p 6666 twitter.com +tcp

> ; <<>> DiG 9.12.4 <<>> @127.0.0.1 -p 6666 twitter.com +tcp
> ; (1 server found)
> ;; global options: +cmd
> ;; connection timed out; no servers could be reached

Is rrredir designed to be or bug?

**Comment by rofl0r** [comment]
0.5 is a floating point number. we parse the -t parameter with atoi, which returns an integer. so 0.5 is turned into 0.

if you need finer than second granularity, this modification could work:

```diff
@@hunk1
 static const struct server* server;
-unsigned long timeout;
+float timeout;
 static sblist* targets; 
@@hunk2
                         case 't':
-                                timeout = atoi(optarg);
+                                timeout = atof(optarg);
                                 break;
```

**Comment by rampageX** [comment]
@rofl0r Thanks! It is working!

**Comment by rofl0r** [comment]
@rampageX could you explain your usecase for sub-second timeout resolution ? maybe it's something of interest for others too.

**Comment by rampageX** [comment]
@rofl0r I use rrredir for bypasses DNS-based internet censorship when port 53 is intercepted. 

All upsteams are non-standard port dns server with tcp support, and rrredir give me the best failback and sequential selection logic, and it's lightweight!

I want less timeout because it is used for dns query, so response speed is especially important，actually I am using timeout=0.3 （300ms）now，it's very balance for my case。
